# Generated by Django 3.1.7 on 2021-03-29 11:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='習慣にしたいこと')),
                ('day', models.IntegerField(choices=[(7, '未選択'), (6, '日'), (0, '月'), (1, '火'), (2, '水'), (3, '木'), (4, '金'), (5, '土')], default=None, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='曜日')),
                ('date', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(31)], verbose_name='毎月○日')),
                ('interval', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='○日間隔')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
