# Generated by Django 3.1.7 on 2021-04-01 14:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('star_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='create_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='work',
            name='day',
            field=models.IntegerField(choices=[(7, '未選択'), (6, '日'), (0, '月'), (1, '火'), (2, '水'), (3, '木'), (4, '金'), (5, '土')], default=None, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='曜日'),
        ),
    ]
