# Generated by Django 3.0.14 on 2021-05-10 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('star_app', '0002_auto_20210401_2320'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('calcium', models.CharField(max_length=100)),
                ('calorie', models.CharField(max_length=100)),
                ('carbohydrate', models.CharField(max_length=100)),
                ('dietary_fiber', models.CharField(max_length=100)),
                ('fat', models.CharField(max_length=100)),
                ('food_id', models.CharField(max_length=100)),
                ('food_name', models.CharField(max_length=300)),
                ('potassium', models.CharField(max_length=100)),
                ('protein', models.CharField(max_length=100)),
                ('salt', models.CharField(max_length=100)),
                ('sodium', models.CharField(max_length=100)),
                ('vitamin_a', models.CharField(max_length=100)),
                ('vitamin_c', models.CharField(max_length=100)),
                ('vitamin_d', models.CharField(max_length=100)),
                ('vitamin_e', models.CharField(max_length=100)),
                ('vitamin_k', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
