# Generated by Django 3.0.14 on 2021-05-10 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('star_app', '0003_meal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='user',
        ),
        migrations.AddField(
            model_name='meal',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
