# Generated by Django 3.0.14 on 2021-05-17 23:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('star_app', '0004_auto_20210510_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='weight',
            field=models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
